sudo: required
services:
  - docker

before_install:
  - docker build -t asus/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true asus/docker-react npm run test

language: generic

# deploy:
#   provider : elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#   bucket_path: "docker"
#   on:
#     branch: master
# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY

